version: '1.0'
name: to_releases
displayName: releases
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
    paths:
      precise:
        - setup.py
stages:
  - name: stage-494a5a4f
    displayName: python
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - '# pip install --user -r requirements.txt'
          - sha256sum setup.py | cut -c 1-64 > ErrorHook/hash.file
          - python -m pip install --upgrade build
          - python -m pip install twine
          - python -m build
          - python -m twine upload dist/* --password pypi-AgEIcHlwaS5vcmcCJDA3MTlmNzIwLThhMGQtNDgxOS05NzBlLTEzY2ZlODEwNjg0MAACKlszLCIwYWYyNmM2Ni03MjBhLTQxY2EtYjFkOS00NzMzYTg3NzM2ZjQiXQAABiBUEGqEU1xsOpyIGbMdzmYLyEOIvkjOFrHujzWFysdv7Q
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - dist/
        caches: []
        notify:
          - certificate: b3b564d0-256b-013d-545e-5a5752d4d677
            events:
              - success
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - operator
              - branch
              - detail
            type: feishu
        strategy:
          retry: '0'
  - name: stage-cb1703e2
    displayName: gitee
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        notify: []
        strategy:
          retry: '0'
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 2.2.8.0
        autoIncrement: true
        notify:
          - certificate: b3b564d0-256b-013d-545e-5a5752d4d677
            events:
              - success
              - fail
            content:
              - repository
              - pipeline
              - stage
              - task
              - detail
            type: feishu
        strategy:
          retry: '0'
        dependsOn: publish_general_artifacts
strategy:
  blocking: true
