version: '1.0'
name: to_releases
displayName: releases
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
    paths:
      precise:
        - dist/
stages:
  - name: stage-494a5a4f
    displayName: releases
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 2.2.4.0
        autoIncrement: true
        notify: []
        strategy:
          retry: '0'
